question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "Water boils at 100 degrees Celsius.", "answer": "True"},
    {"text": "The Atlantic Ocean is the largest ocean on Earth.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Goldfish have a 3-second memory.", "answer": "False"},
    {"text": "Bulls are enraged by the color red.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain on Earth.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Chameleons change color to blend in with their surroundings.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The sun is a planet.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The longest river in the world is the Amazon.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "A year on Mercury is longer than a day on Mercury.", "answer": "False"},
    {"text": "Dolphins sleep with one eye open.", "answer": "True"},
    {"text": "The human nose can detect over 1 trillion scents.", "answer": "True"},
    {"text": "Strawberries are berries.", "answer": "False"},
    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "Elephants are the only animals that can't jump.", "answer": "False"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "Tigers have striped skin, not just striped fur.", "answer": "True"},
    {"text": "The Pacific Ocean is larger than all of Earth's land combined.", "answer": "True"},
    {"text": "Polar bears have black skin.", "answer": "True"},
    {"text": "Houseflies hum in the key of F.", "answer": "True"},
    {"text": "A group of crows is called a 'murder'.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "The moon has its own light.", "answer": "False"},
    {"text": "Humans can sneeze with their eyes open.", "answer": "False"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},
    {"text": "Antarctica is the driest continent.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "The human stomach produces a new layer of mucus every two weeks.", "answer": "True"},
    {"text": "Coca-Cola was originally green.", "answer": "False"},
    {"text": "The first oranges weren't orange.", "answer": "True"},
    {"text": "Peanuts are nuts.", "answer": "False"},
    {"text": "Alaska is the largest US state by area.", "answer": "True"},
    {"text": "The tongue is the strongest muscle in the human body.", "answer": "False"},
    {"text": "A bolt of lightning is five times hotter than the surface of the sun.", "answer": "True"},
    {"text": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", "answer": "True"},
    {"text": "There are more possible iterations of a game of chess than there are atoms in the known universe.", "answer": "True"},
    {"text": "The inventor of the Pringles can is buried in one.", "answer": "True"},
    {"text": "A cloud can weigh more than a million pounds.", "answer": "True"},
    {"text": "Hot water freezes faster than cold water.", "answer": "True"},
    {"text": "Mosquitoes are the deadliest animal to humans.", "answer": "True"},
    {"text": "The Mona Lisa has no eyebrows.", "answer": "True"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "There are more trees on Earth than stars in the Milky Way galaxy.", "answer": "True"},
    {"text": "Your brain uses 20% of your body's oxygen.", "answer": "True"},
    {"text": "The human eye can see the Andromeda galaxy.", "answer": "True"},
    {"text": "Sharks existed before trees.", "answer": "True"},
    {"text": "The inventor of the frisbee was turned into a frisbee after he died.", "answer": "True"},
    {"text": "A group of pugs is called a 'grumble'.", "answer": "True"},
    {"text": "Scotland's national animal is a dragon.", "answer": "False"},
    {"text": "Sharks are older than Saturn's rings.", "answer": "True"},
    {"text": "The King of Hearts is the only king without a mustache in a standard deck of cards.", "answer": "True"},
    {"text": "A jiffy is an actual unit of time.", "answer": "True"},
    {"text": "Mammals cannot breathe and swallow at the same time.", "answer": "False"},
    {"text": "The hashtag symbol is technically called an octothorpe.", "answer": "True"},
    {"text": "Some cats are allergic to humans.", "answer": "True"},
    {"text": "The shortest complete sentence in the English language is 'Go'.", "answer": "False"},
    {"text": "Fingerprints of koalas are similar to humans.", "answer": "True"},
    {"text": "Sloths can hold their breath longer than dolphins.", "answer": "True"},
    {"text": "A blue whale's heart is the size of a small car.", "answer": "True"},
    {"text": "Avocados are toxic to birds.", "answer": "True"},
    {"text": "The shortest war lasted 45 minutes.", "answer": "False"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "Butterflies can taste with their feet.", "answer": "True"},
    {"text": "The letter Q does not appear in any US state name.", "answer": "True"},
    {"text": "Sea otters hold hands when they sleep.", "answer": "True"},
    {"text": "A group of jellyfish is called a 'smack'.", "answer": "True"},
    {"text": "Humans and giraffes have the same number of neck bones.", "answer": "True"},
    {"text": "The dot over the letter 'i' is called a tittle.", "answer": "True"},
    {"text": "Turtles can breathe through their butts.", "answer": "True"},
    {"text": "Cows have best friends.", "answer": "True"},
    {"text": "There are more fake flamingos in the world than real ones.", "answer": "True"},
    {"text": "Your nose and ears never stop growing.", "answer": "True"},
    {"text": "A single strand of spaghetti is called a 'spaghetto'.", "answer": "True"},
    {"text": "Armadillos can get leprosy.", "answer": "True"},
    {"text": "The fear of long words is called hippopotomonstrosesquippedaliophobia.", "answer": "True"},
    {"text": "A group of owls is called a 'parliament'.", "answer": "True"},
    {"text": "Koalas sleep 22 hours a day.", "answer": "True"},
    {"text": "The inventor of the microwave oven only received $2 for his discovery.", "answer": "True"},
    {"text": "Apples float in water because they are 25% air.", "answer": "True"},
    {"text": "Humans are the only animals that blush.", "answer": "True"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "The average person walks the equivalent of five times around the world in their lifetime.", "answer": "True"},
    {"text": "Rats laugh when tickled.", "answer": "True"},
    {"text": "The world's oldest wooden wheel is over 5,000 years old.", "answer": "True"},
    {"text": "Jellyfish are 95% water.", "answer": "True"},
    {"text": "Polar bears are left-handed.", "answer": "False"},
    {"text": "A hummingbird weighs less than a penny.", "answer": "True"},
    {"text": "The Twitter bird's name is Larry.", "answer": "True"},
    {"text": "Lemons float, but limes sink.", "answer": "True"},
    {"text": "A giraffe can clean its ears with its tongue.", "answer": "True"},
    {"text": "Pigs cannot look up at the sky.", "answer": "True"},
    {"text": "The world's largest desert is Antarctica.", "answer": "True"},
    {"text": "Horses cannot vomit.", "answer": "True"},
    {"text": "The average cloud weighs about 1.1 million pounds.", "answer": "True"},
    {"text": "A crocodile cannot stick its tongue out.", "answer": "True"},
    {"text": "You burn more calories sleeping than watching television.", "answer": "True"},
    {"text": "The inventor of the electric chair was a dentist.", "answer": "True"},
    {"text": "Lobsters are immortal.", "answer": "False"},
    {"text": "The wood frog can hold its pee for up to eight months.", "answer": "True"},
    {"text": "A group of hedgehogs is called a 'prickle'.", "answer": "True"},
    {"text": "The world's quietest room is so quiet you can hear your own blood flow.", "answer": "True"},
    {"text": "Cleopatra was Greek, not Egyptian.", "answer": "True"},
    {"text": "The longest English word without a vowel is 'rhythms'.", "answer": "True"},
    {"text": "A blue moon occurs once every 2.7 years.", "answer": "True"},
    {"text": "The average person spends six months of their life waiting for red lights to turn green.", "answer": "True"},
    {"text": "Hippopotamus milk is pink.", "answer": "True"},
    {"text": "A sneeze travels at about 100 miles per hour.", "answer": "True"},
    {"text": "The world's longest place name has 85 letters.", "answer": "True"},
    {"text": "Otters have pockets in their skin to store their favorite rocks.", "answer": "True"},
    {"text": "The first computer bug was an actual bug.", "answer": "True"},
    {"text": "Banging your head against a wall burns 150 calories an hour.", "answer": "True"},
    {"text": "A bolt of lightning contains enough energy to toast 100,000 slices of bread.", "answer": "True"},
    {"text": "The fear of vegetables is called lachanophobia.", "answer": "True"},
    {"text": "A pig's orgasm lasts 30 minutes.", "answer": "True"},
    {"text": "The world's smallest mammal is the bumblebee bat.", "answer": "True"},
    {"text": "You can't hum while holding your nose.", "answer": "True"},
    {"text": "The moon is moving away from Earth at 3.8 cm per year.", "answer": "True"},
    {"text": "Dolphins have names for each other.", "answer": "True"},
    {"text": "A flock of ravens is called an 'unkindness'.", "answer": "True"},
    {"text": "The human brain is 80% water.", "answer": "True"},
    {"text": "Cows produce more milk when they listen to slow music.", "answer": "True"},
    {"text": "Peanut butter can be converted into diamonds.", "answer": "True"},
    {"text": "The world's oldest known recipe is for beer.", "answer": "True"},
    {"text": "Butterflies have two stomachs.", "answer": "True"},
    {"text": "You are more likely to be killed by a vending machine than a shark.", "answer": "True"},
    {"text": "A group of ferrets is called a 'business'.", "answer": "True"},
    {"text": "There are more statues of lions in the world than there are real lions.", "answer": "True"},
    {"text": "The world's largest snowflake was 15 inches wide.", "answer": "True"},
    {"text": "Cats can rotate their ears 180 degrees.", "answer": "True"},
    {"text": "The first alarm clock could only ring at 4 a.m.", "answer": "True"},
    {"text": "Your heart beats about 100,000 times a day.", "answer": "True"},
    {"text": "The fear of being without your phone is called nomophobia.", "answer": "True"},
    {"text": "Penguins propose to their mates with a pebble.", "answer": "True"},
    {"text": "The average person has 67 different species of bacteria in their belly button.", "answer": "True"},
    {"text": "A chicken lived for 18 months without a head.", "answer": "True"},
    {"text": "The world's oldest piece of chewing gum is over 9,000 years old.", "answer": "True"},
    {"text": "You cannot snore and dream at the same time.", "answer": "True"},
    {"text": "Spiders can survive for weeks without their heads.", "answer": "False"},
    {"text": "The longest hiccuping spree lasted 68 years.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "You can't breathe and swallow at the same time.", "answer": "True"},
    {"text": "The world's oldest known goldfish lived to 43 years old.", "answer": "True"},
    {"text": "A group of unicorns is called a 'blessing'.", "answer": "True"},
    {"text": "The average person will spend 25 years sleeping.", "answer": "True"},
    {"text": "A duck's quack doesn't echo.", "answer": "False"},
    {"text": "The world's heaviest onion weighed over 18 pounds.", "answer": "True"},
    {"text": "Elephants can't jump because they're too heavy.", "answer": "False"},
    {"text": "The shortest commercial flight in the world is 57 seconds.", "answer": "True"},
    {"text": "Cows kill more people than sharks do.", "answer": "True"},
    {"text": "A group of crows is more intelligent than a 7-year-old human.", "answer": "True"},
    {"text": "The world's largest grand piano was built by a 15-year-old in New Zealand.", "answer": "True"},
    {"text": "You can hear a blue whale's heartbeat from 2 miles away.", "answer": "True"},
    {"text": "Ants never sleep.", "answer": "True"},
    {"text": "The world's deepest postbox is in Susami Bay, Japan, at 10 meters underwater.", "answer": "True"},
    {"text": "A group of kangaroos is called a 'mob'.", "answer": "True"},
    {"text": "Your body produces enough heat in 30 minutes to boil half a gallon of water.", "answer": "True"},
    {"text": "The world's largest jigsaw puzzle has 551,232 pieces.", "answer": "True"},
    {"text": "Snails have 14,000 teeth.", "answer": "True"},
    {"text": "The average person eats 8 spiders in their sleep per year.", "answer": "False"},
    {"text": "A cat has 32 muscles in each ear.", "answer": "True"},
    {"text": "The world's tallest man was 8 feet 11 inches.", "answer": "True"},
    {"text": "Honey is the only food that doesn't spoil.", "answer": "False"},
    {"text": "The longest recorded flight of a chicken is 13 seconds.", "answer": "True"},
    {"text": "A group of porcupines is called a 'prickle'.", "answer": "True"},
    {"text": "The shortest person ever recorded was 21.5 inches tall.", "answer": "True"},
    {"text": "You lose about 50-100 hairs every day.", "answer": "True"},
    {"text": "The world's oldest living tree is over 5,000 years old.", "answer": "True"},
    {"text": "A giraffe's tongue is black to prevent sunburn.", "answer": "True"},
    {"text": "The average person farts 14 times a day.", "answer": "True"},
]