data = [
    {"name": "Instagram", "followers": 660000000, "description": "Social media platform", "country": "United States"},
    {"name": "Cristiano Ronaldo", "followers": 600000000, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 490000000, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "followers": 430000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kylie Jenner", "followers": 400000000, "description": "Reality TV star and businesswoman", "country": "United States"},
    {"name": "Dwayne Johnson", "followers": 390000000, "description": "Actor and former wrestler", "country": "United States"},
    {"name": "Ariana Grande", "followers": 380000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Kim Kardashian", "followers": 360000000, "description": "Reality TV star and businesswoman", "country": "United States"},
    {"name": "Beyoncé", "followers": 315000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Khloé Kardashian", "followers": 310000000, "description": "Reality TV star", "country": "United States"},
    {"name": "Nike", "followers": 305000000, "description": "Sportswear brand", "country": "United States"},
    {"name": "Justin Bieber", "followers": 295000000, "description": "Singer", "country": "Canada"},
    {"name": "Kendall Jenner", "followers": 290000000, "description": "Model and reality TV star", "country": "United States"},
    {"name": "Taylor Swift", "followers": 280000000, "description": "Singer-songwriter", "country": "United States"},
    {"name": "National Geographic", "followers": 280000000, "description": "Media company", "country": "United States"},
    {"name": "Virat Kohli", "followers": 265000000, "description": "Cricketer", "country": "India"},
    {"name": "Jennifer Lopez", "followers": 250000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Nicki Minaj", "followers": 230000000, "description": "Rapper and singer", "country": "Trinidad and Tobago"},
    {"name": "Kourtney Kardashian", "followers": 225000000, "description": "Reality TV star", "country": "United States"},
    {"name": "Miley Cyrus", "followers": 215000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Katy Perry", "followers": 205000000, "description": "Singer", "country": "United States"},
    {"name": "Zendaya", "followers": 185000000, "description": "Actress and singer", "country": "United States"},
    {"name": "Kevin Hart", "followers": 180000000, "description": "Comedian and actor", "country": "United States"},
    {"name": "Cardi B", "followers": 165000000, "description": "Rapper", "country": "United States"},
    {"name": "LeBron James", "followers": 160000000, "description": "Basketball player", "country": "United States"},
    {"name": "Rihanna", "followers": 152000000, "description": "Singer and businesswoman", "country": "Barbados"},
    {"name": "Demi Lovato", "followers": 155000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Real Madrid CF", "followers": 150000000, "description": "Football club", "country": "Spain"},
    {"name": "FC Barcelona", "followers": 125000000, "description": "Football club", "country": "Spain"},
    {"name": "Neymar Jr", "followers": 220000000, "description": "Footballer", "country": "Brazil"},
    {"name": "Chris Brown", "followers": 145000000, "description": "Singer", "country": "United States"},
    {"name": "Drake", "followers": 145000000, "description": "Rapper", "country": "Canada"},
    {"name": "Billie Eilish", "followers": 110000000, "description": "Singer", "country": "United States"},
    {"name": "Snoop Dogg", "followers": 85000000, "description": "Rapper", "country": "United States"},
    {"name": "Emma Watson", "followers": 75000000, "description": "Actress", "country": "United Kingdom"},
    {"name": "Shakira", "followers": 90000000, "description": "Singer", "country": "Colombia"},
    {"name": "Shawn Mendes", "followers": 73000000, "description": "Singer", "country": "Canada"},
    {"name": "Camila Cabello", "followers": 65000000, "description": "Singer", "country": "Cuba"},
    {"name": "NASA", "followers": 95000000, "description": "Space agency", "country": "United States"},
    {"name": "Priyanka Chopra", "followers": 90000000, "description": "Actress", "country": "India"},
    {"name": "Shraddha Kapoor", "followers": 80000000, "description": "Actress", "country": "India"},
    {"name": "Alia Bhatt", "followers": 82000000, "description": "Actress", "country": "India"},
    {"name": "Deepika Padukone", "followers": 78000000, "description": "Actress", "country": "India"},
    {"name": "Katrina Kaif", "followers": 76000000, "description": "Actress", "country": "India"},
    {"name": "Ronaldinho", "followers": 74000000, "description": "Former footballer", "country": "Brazil"},
    {"name": "Zlatan Ibrahimović", "followers": 62000000, "description": "Footballer", "country": "Sweden"},
    {"name": "David Beckham", "followers": 87000000, "description": "Former footballer", "country": "United Kingdom"},
    {"name": "Gigi Hadid", "followers": 79000000, "description": "Model", "country": "United States"},
    {"name": "Bella Hadid", "followers": 60000000, "description": "Model", "country": "United States"},
    {"name": "Cara Delevingne", "followers": 44000000, "description": "Model and actress", "country": "United Kingdom"},
    {"name": "Margot Robbie", "followers": 29000000, "description": "Actress", "country": "Australia"},
    {"name": "Will Smith", "followers": 72000000, "description": "Actor", "country": "United States"},
    {"name": "Dua Lipa", "followers": 88000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Adele", "followers": 54000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Lady Gaga", "followers": 56000000, "description": "Singer and actress", "country": "United States"},
    {"name": "Bruno Mars", "followers": 32000000, "description": "Singer", "country": "United States"},
    {"name": "The Weeknd", "followers": 58000000, "description": "Singer", "country": "Canada"},
    {"name": "Post Malone", "followers": 30000000, "description": "Rapper and singer", "country": "United States"},
    {"name": "Travis Scott", "followers": 56000000, "description": "Rapper", "country": "United States"},
    {"name": "J Balvin", "followers": 58000000, "description": "Singer", "country": "Colombia"},
    {"name": "Bad Bunny", "followers": 47000000, "description": "Rapper and singer", "country": "Puerto Rico"},
    {"name": "Maluma", "followers": 64000000, "description": "Singer", "country": "Colombia"},
    {"name": "Anitta", "followers": 64000000, "description": "Singer", "country": "Brazil"},
    {"name": "Nicki Nicole", "followers": 6000000, "description": "Singer", "country": "Argentina"},
    {"name": "Doja Cat", "followers": 26000000, "description": "Rapper and singer", "country": "United States"},
    {"name": "Megan Thee Stallion", "followers": 31000000, "description": "Rapper", "country": "United States"},
    {"name": "Lizzo", "followers": 13000000, "description": "Singer and rapper", "country": "United States"},
    {"name": "SZA", "followers": 19000000, "description": "Singer", "country": "United States"},
    {"name": "H.E.R.", "followers": 7000000, "description": "Singer", "country": "United States"},
    {"name": "Jhené Aiko", "followers": 9000000, "description": "Singer", "country": "United States"},
    {"name": "Kehlani", "followers": 14000000, "description": "Singer", "country": "United States"},
    {"name": "Summer Walker", "followers": 7000000, "description": "Singer", "country": "United States"},
    {"name": "Ava Max", "followers": 9000000, "description": "Singer", "country": "United States"},
    {"name": "Bebe Rexha", "followers": 18000000, "description": "Singer", "country": "United States"},
    {"name": "Halsey", "followers": 32000000, "description": "Singer", "country": "United States"},
    {"name": "Lana Del Rey", "followers": 23000000, "description": "Singer", "country": "United States"},
    {"name": "Lorde", "followers": 11000000, "description": "Singer", "country": "New Zealand"},
    {"name": "Charli XCX", "followers": 5000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Troye Sivan", "followers": 17000000, "description": "Singer and actor", "country": "Australia"},
    {"name": "Sam Smith", "followers": 15000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Ed Sheeran", "followers": 42000000, "description": "Singer-songwriter", "country": "United Kingdom"},
    {"name": "Harry Styles", "followers": 48000000, "description": "Singer and actor", "country": "United Kingdom"},
    {"name": "Zayn Malik", "followers": 50000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Niall Horan", "followers": 29000000, "description": "Singer", "country": "Ireland"},
    {"name": "Louis Tomlinson", "followers": 18000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "Liam Payne", "followers": 24000000, "description": "Singer", "country": "United Kingdom"},
    {"name": "BTS", "followers": 75000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "BLACKPINK", "followers": 53000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Lisa (BLACKPINK)", "followers": 100000000, "description": "K-pop idol", "country": "Thailand"},
    {"name": "Jennie Kim", "followers": 79000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Jisoo", "followers": 74000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Rosé", "followers": 77000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Jungkook", "followers": 55000000, "description": "K-pop idol (BTS)", "country": "South Korea"},
    {"name": "V (BTS)", "followers": 62000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Jimin (BTS)", "followers": 52000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Suga (BTS)", "followers": 42000000, "description": "K-pop idol and rapper", "country": "South Korea"},
    {"name": "RM (BTS)", "followers": 46000000, "description": "K-pop idol and rapper", "country": "South Korea"},
    {"name": "J-Hope (BTS)", "followers": 47000000, "description": "K-pop idol and rapper", "country": "South Korea"},
    {"name": "Jin (BTS)", "followers": 49000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "EXO", "followers": 12000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "TWICE", "followers": 16000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Stray Kids", "followers": 15000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "SEVENTEEN", "followers": 14000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "NCT", "followers": 11000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Red Velvet", "followers": 9000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Mamamoo", "followers": 6000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "GOT7", "followers": 11000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Monsta X", "followers": 8000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "ITZY", "followers": 14000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "Aespa", "followers": 11000000, "description": "K-pop group", "country": "South Korea"},
    {"name": "IU", "followers": 30000000, "description": "K-pop singer and actress", "country": "South Korea"},
    {"name": "Taehyung", "followers": 6000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Jeno", "followers": 8000000, "description": "K-pop idol (NCT)", "country": "South Korea"},
    {"name": "Mark Lee", "followers": 10000000, "description": "K-pop idol (NCT)", "country": "South Korea"},
    {"name": "Felix (Stray Kids)", "followers": 11000000, "description": "K-pop idol", "country": "Australia"},
    {"name": "Hyunjin (Stray Kids)", "followers": 13000000, "description": "K-pop idol", "country": "South Korea"},
    {"name": "Bang Chan", "followers": 9000000, "description": "K-pop idol (Stray Kids)", "country": "Australia"},
    {"name": "Woozi", "followers": 7000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "Joshua", "followers": 8000000, "description": "K-pop idol (SEVENTEEN)", "country": "United States"},
    {"name": "DK", "followers": 7000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "Mingyu", "followers": 12000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "The8", "followers": 9000000, "description": "K-pop idol (SEVENTEEN)", "country": "China"},
    {"name": "Dino", "followers": 6000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "Hoshi", "followers": 7000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "Wonwoo", "followers": 9000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "S.Coups", "followers": 8000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "Vernon", "followers": 8000000, "description": "K-pop idol (SEVENTEEN)", "country": "United States"},
    {"name": "Jeonghan", "followers": 9000000, "description": "K-pop idol (SEVENTEEN)", "country": "South Korea"},
    {"name": "Jun", "followers": 7000000, "description": "K-pop idol (SEVENTEEN)", "country": "China"},
]